### ISSUE TITLE
Built-in OAuth app appears to have been shutdown

### ISSUE THREAD

**Issue by jennybc** [andrie/gcalendr#10]
I am not surprised that the app is defunct. It's very hard to do this now (include an app). For some APIs it's essentially impossible to get an app verified and unverified apps are shut down after a certain number of uses or a certain number of distinct users.

You may need to insist that users bring their own auth app, like gmailr now does:

https://gmailr.r-lib.org/#setup

**Comment by andrie** [comment]
Yes, thank you.  I burnt all my GCP projects down to the ground and started with a clean slate.  This is fixed now.

**Comment by jennybc** [comment]
I suspect the new app will get shutdown by Google in the future, unless you go through the verification process. I think the trigger is something like `n` uses of the app or `n` uses by unique Google users. So it will work for a little while and then stop.

I think there's no long-term way to avoid either getting verified or officially encouraging users to get their own app.
