### ISSUE TITLE
Rename all functions to `calendar_...()`

### ISSUE THREAD

**Issue by andrie** [andrie/gcalendr#4]
The `googledrive` package uses the convention with function names starting with `drive_...()`.

I propose to rename all the functions to `calendar_...()` instead of `gcalendr_...()`.

This is:

* easier to type and read
* and thus potentially less prone to errors

**Comment by msberends** [comment]
I politely want to oppose against the idea of prefixing all functions within a package with a package name or anything like it (like `calendar_`).

I personally find all prefixes of e.g. the `stringr` package (`str_`) very, very annoying and unneeded. If we all proceed with this, we will end up using functions like `dplr_group_by` and `dplr_summarise` to do our daily work. Would be a shame of the beautifully concise R language :smile:

**Comment by andrie** [comment]
Noted. Thank you.
